enum LetterStatusEnum {
  ARCHIVED = 1,
  CANCELLED = 2,
  COMPLETED = 3,
  DRAFT = 4,
  DRAFT_PENDING_REVIEW = 5,
  DRAFT_REVIEWED = 6,
  DRAFT_UNDER_REVIEW = 7,
  FORWARDED_PENDING_REVIEW = 8,
  FORWARDED_REVIEWED = 9,
  FORWARDED_UNDER_REVIEW = 10,
  PENDING_APPROVAL = 11,
  PUBLISHED = 12,
}

export default LetterStatusEnum;
