export enum LetterTableColumnEnum {
  ID = "id",
  REFERENCE_NUMBER = "reference_number",
  HAS_READ = "has_read",
  SUBJECT = "subject",
  CURRENT_STATE = "current_state",
  SENDER = "sender",
  RECIPIENT = "recipient",
  LETTER_TYPE = "letter_type",
  RECEIVED_AT = "received_at",
  SUBMITTED_AT = "submitted_at",
  PUBLISHED_AT = "published_at",
  CREATED_AT = "created_at",
  UPDATED_AT = "updated_at",
}
